In [472]:
## 22 광주 23 김천 24 안양 25 인천 ## 21 김천

## 만들어야하는 버튼
    ## 현재라운드와 비교
    ## 전체비교

In [473]:
import pandas as pd
import pickle

In [ ]:
## data cleaning
ctrl_cv = pd.read_excel("raw data.xlsx", engine='openpyxl', sheet_name= '역대 2부리그')
# ctrl_cv.head()

   round  season  point
0      1    2022      0
1      2    2022      3
2      3    2022      3
3      4    2022      3
4      5    2022      0

In [ ]:
hist_winner = ctrl_cv.copy()
# hist_winner

     round  season  point
0        1    2022      0
1        2    2022      3
2        3    2022      3
3        4    2022      3
4        5    2022      0
..     ...     ...    ...
143     32    2021      3
144     33    2021      1
145     34    2021      3
146     35    2021      3
147     36    2021      1

[148 rows x 3 columns]

In [ ]:
season_team ={ 2021:'김천',
               2022:'광주',
               2023:'김천',
               2024:'안양'}

{2021: '김천', 2022: '광주', 2023: '김천', 2024: '안양'}

In [ ]:
hist_winner['team_name'] = hist_winner['season'].map(season_team)
# hist_winner.head()

   round  season  point team_name
0      1    2022      0        광주
1      2    2022      3        광주
2      3    2022      3        광주
3      4    2022      3        광주
4      5    2022      0        광주

In [ ]:
hist_winner['cum_point'] = hist_winner.groupby(['season','team_name'])['point'].cumsum()
# hist_winner.head()

   round  season  point team_name  cum_point
0      1    2022      0        광주          0
1      2    2022      3        광주          3
2      3    2022      3        광주          6
3      4    2022      3        광주          9
4      5    2022      0        광주          9

In [ ]:
hist_winner['team'] = hist_winner.apply(lambda x: str(x['season'])+ ' ' + x['team_name'], axis=1)
# hist_winner.head()

   round  season  point team_name  cum_point     team
0      1    2022      0        광주          0  2022 광주
1      2    2022      3        광주          3  2022 광주
2      3    2022      3        광주          6  2022 광주
3      4    2022      3        광주          9  2022 광주
4      5    2022      0        광주          9  2022 광주

In [ ]:
hist_winner = hist_winner[['round','team','cum_point']]
# hist_winner.head()

   round     team  cum_point
0      1  2022 광주          0
1      2  2022 광주          3
2      3  2022 광주          6
3      4  2022 광주          9
4      5  2022 광주          9

In [ ]:
## current season cleaning
ctrl_cv2 = pd.read_excel("raw data.xlsx", engine='openpyxl', sheet_name='25시즌')
# ctrl_cv2.head()

   순번  경기번호         일자 홈/원정   팀  얻은 승점
0   1     1 2025-02-22    H  경남      0
1   2     1 2025-02-22    A  인천      3
2   3     2 2025-02-22    A  천안      0
3   4     2 2025-02-22    H  전남      3
4   5     3 2025-02-22    H  김포      1

In [ ]:
current_season = ctrl_cv2.copy()

current_season['round'] = current_season.groupby(['팀'])['일자'].rank()
current_season['round'] =current_season['round'].apply(lambda x : int(x))

# current_season.head()

   순번  경기번호         일자 홈/원정   팀  얻은 승점  round
0   1     1 2025-02-22    H  경남      0      1
1   2     1 2025-02-22    A  인천      3      1
2   3     2 2025-02-22    A  천안      0      1
3   4     2 2025-02-22    H  전남      3      1
4   5     3 2025-02-22    H  김포      1      1

In [ ]:
current_season['cum_point'] = current_season.groupby(['팀'])['얻은 승점'].cumsum()
# current_season.head()

   순번  경기번호         일자 홈/원정   팀  얻은 승점  round  cum_point
0   1     1 2025-02-22    H  경남      0      1          0
1   2     1 2025-02-22    A  인천      3      1          3
2   3     2 2025-02-22    A  천안      0      1          0
3   4     2 2025-02-22    H  전남      3      1          3
4   5     3 2025-02-22    H  김포      1      1          1

In [ ]:
current_season = current_season[['round', '팀', 'cum_point']]
# current_season.head()

   round   팀  cum_point
0      1  경남          0
1      1  인천          3
2      1  천안          0
3      1  전남          3
4      1  김포          1

In [485]:
# ## save current season data 
# with open('current_season.pickle', 'wb') as fw:
#     pickle.dump(current_season, fw)

In [486]:
## current season update need

In [487]:
round17 = pd.read_excel("raw data.xlsx", engine='openpyxl', sheet_name='17round')

In [ ]:
current_season = pd.concat([current_season, round17], ignore_index= True)
# current_season.head()

   round   팀  cum_point
0      1  경남          0
1      1  인천          3
2      1  천안          0
3      1  전남          3
4      1  김포          1

In [489]:
# ## save current season data 
# with open('current_season.pickle', 'wb') as fw:
#     pickle.dump(current_season, fw)

In [490]:
########################################################## 여기서부터시작!

In [491]:
import pandas as pd
import altair as alt
import pickle
import voila

In [493]:
## team color
color_dict = {
    '경남': '#E83827',
    '인천': '#1C6CB2',
    '천안': '#5EB3E4', 
    '전남': '#FFDC00', 
    '김포': '#203D41', 
    '부산': '#B20518', 
    '안산': '#009C7D', 
    '수원': '#0058A6', 
    '화성': '#E8551E', 
    '성남': '#000000', 
    '충남아산': '#F4CE15',
    '서울E': '#00042E', 
    '충북청주': '#1C235A', 
    '부천': '#BE4040'

}

In [494]:
# ## save data
# with open('hist_winner.pickle', 'wb') as fw:
#     pickle.dump(hist_winner, fw)

In [495]:
## load data
with open('hist_winner.pickle', 'rb') as fr:
    hist_winner = pickle.load(fr)

In [497]:
## load data
with open('current_season.pickle', 'rb') as fr:
    current_season = pickle.load(fr)

In [499]:
current_round = current_season['round'].max()

In [500]:
# current_round = 16


input_radio = alt.binding_radio(
    options = [current_round, 40], 
    labels= ['현재 라운드', '전체 라운드'],
    name ='라운드 별 보기'
)
# slider = alt.binding_range(min=1, max=40, step = 1)
round_selection = alt.param( bind = input_radio, value = current_round)

base_line= (
    alt.
    Chart(hist_winner).
    transform_filter(
        alt.datum.team != '2021 김천'
    ).
    transform_filter(
        # alt.datum.round <= current_round
        alt.datum.round <= round_selection
    ).
    encode(
        x = alt.X('round').axis(title = 'Round'),
        y = alt.Y('cum_point').axis(title = 'Point'),
        detail = 'team',
        text = 'team',
        tooltip= alt.Tooltip(['team', 'cum_point'])
    ).
    mark_line(color = 'lightgray')
).add_params(round_selection)

label = (
    alt.
    Chart(hist_winner).
    transform_filter(
        alt.datum.team != '2021 김천'
    ).
    transform_filter(
        alt.datum.round <= round_selection
    ).
    encode(
        x = 'max(round):Q',
        y = alt.Y('cum_point').aggregate(argmax='round'),
        text = 'team',
        detail='team'
    )
).add_params(round_selection)

base_text = (
    label.
    mark_text(align='left', dx = 4, color = 'gray')
)

base_circle = (
    label.
    mark_circle(color = 'gray')
)

base_chart  = (
    alt.layer(
        base_line, 
        base_text, 
        base_circle)
)

base_chart = base_chart.properties(
    width = 700,
    height = 400
# ).configure_view(
#     stroke = None
# ).configure_axis(
#     grid = False,
#     ticks  = False,
#     # labels  = False,
)

In [501]:
selector = alt.selection_point(fields= ['팀'], value = '인천')

cur_rank = list(current_season[current_season['round']==current_round].sort_values('cum_point', ascending = False)['팀'])

cur_season_Chart = (
    alt.
    Chart(current_season).
    transform_filter(
        selector
    ).
    encode(
        x = 'round',
        y = 'cum_point',
        # detail = alt.Detail('팀'),
        color = alt.Color('팀').scale(domain = list(color_dict.keys()), range = list(color_dict.values())).legend(None),
        tooltip= alt.Tooltip(['팀','cum_point'])
    ).
    mark_line()
).add_params(selector)
##
main_label = (
    alt.
    Chart(current_season).
    transform_calculate(
        season_team =  "2025 + datum.팀"
    ).
    encode(
        x = 'max(round):Q',
        y = alt.Y('cum_point').aggregate(argmax='round'),
        color = alt.Color('팀').scale(domain = list(color_dict.keys()), range = list(color_dict.values())).legend(None),
        text = alt.Text("season_team:N"),
        detail='팀'
    )
).add_params(selector).transform_filter(selector)

main_text = (
    main_label.
    
    mark_text(align='left', dx = 4)
)

main_circle = (
    main_label.
    mark_circle()
)

main_chart = (
    alt.layer(
        cur_season_Chart,
        main_text,
        main_circle
    )
)
##


index_point = (
    alt.
    Chart(current_season).
    encode(
        y = alt.Y('팀').axis(title=None).sort(cur_rank),
        color = alt.when(selector).then('팀').otherwise(alt.value('lightgray')),
        # order = alt.Order('팀', sort = 'descending')
    ).
    mark_circle(size = 220)
).add_params(selector).properties(
    width  = 100
)

## Voila Graph Sample

### This is the sample graph using voila.
### It is basically created by Altair, but I can deliver the interactive chart with this way.

### The data is from the K league 2 data for 2025 Season.

In [502]:
final_chart = (
    alt.hconcat(
        alt.layer(
            base_chart,
            main_chart,
        ),
        index_point
    )
)


final_chart.configure_view(
    stroke = None
).configure_axis(
    grid = False,
    ticks  = False,
    # labels  = False,
# ).configure_axisX(
#     grid = False
)

alt.HConcatChart(...)